// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8uBlUHs40meZPn9i-YqHHUkcgJUTAzvA',
    appId: '1:669597302669:web:5f4b699f5d2e0d69f847c4',
    messagingSenderId: '669597302669',
    projectId: 'praktikum19102190',
    authDomain: 'praktikum19102190.firebaseapp.com',
    storageBucket: 'praktikum19102190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBstr3TiznfvdKJ_F4v58BaK3SAZsrT18Y',
    appId: '1:669597302669:android:1b2cb3b8e556af2af847c4',
    messagingSenderId: '669597302669',
    projectId: 'praktikum19102190',
    storageBucket: 'praktikum19102190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVAQV0aYt32IsRHdxc93CbxOOYSgsKZOU',
    appId: '1:669597302669:ios:dc9d8c30b1ca8e7ef847c4',
    messagingSenderId: '669597302669',
    projectId: 'praktikum19102190',
    storageBucket: 'praktikum19102190.appspot.com',
    iosBundleId: 'com.example.praktikum6',
  );
}
